name: Run 2.js

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        type: string
      rate:
        required: true
        type: number
      time:
        required: true
        type: number
      threads:
        required: true
        type: number
      port:
        required: false
        type: number
      data:
        required: false
        type: string
      method:
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install npm dependencies
        run: npm install hpack axios chalk
      - name: Make 2.js executable
        run: chmod +x 2.js
      - name: Run 2.js with parameters
        run: |
          node 2.js "${{ inputs.data }}" "${{ inputs.url }}" "${{ inputs.time }}" "${{ inputs.threads }}" "${{ inputs.rate }}" --query 1 --full true