name: Run us

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        type: string
      rate:
        required: true
        type: number
      time:
        required: true
        type: number
      threads:
        required: true
        type: number
      port:
        required: true
        type: number
      data:
        required: false
        type: string
      method:
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    steps:
      - uses: actions/checkout@v4
      - name: Make us executable
        run: chmod +x us
      - name: Run us with parameters
        run: |
          ./us "${{ inputs.url }}" "${{ inputs.port }}" 88 5 --frag